### ISSUE TITLE
好像没有arm32平台 麻烦博主编译一下

### ISSUE THREAD

**Issue by qingtiandamowang** [luckykeeper/netflowFlasher#1]
好像没有arm32平台 麻烦博主编译一下

**Comment by luckykeeper** [comment]
安排！

**Comment by luckykeeper** [comment]
Releases 上传了 armv6 和 armv7 的二进制文件，Dockerhub 有对应架构的 Docker 镜像，请根据需要使用~

**Comment by luckykeeper** [comment]
由于没有进一步活动，关闭此 issues ，如果有其它问题请开一个新的 issues
